In [43]:
###QUESTION 1

In [44]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [45]:
file_path = '/content/drive/MyDrive/Book1.xlsx'
df = pd.read_excel(file_path)

In [46]:
columns_to_normalize = ["Gender","Age Range","Head Size(cm^3)", "Brain Weight(grams)"]
scaler = MinMaxScaler()
df[columns_to_normalize] = scaler.fit_transform(df[columns_to_normalize])

In [47]:
print(df)

    Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0      0.0        0.0         1.000000             0.842932
1      0.0        0.0         0.275959             0.232984
2      0.0        0.0         0.765201             0.332461
3      0.0        0.0         0.312442             0.193717
4      0.0        0.0         0.686623             1.000000
5      0.0        0.0         0.132834             0.240838
6      0.0        0.0         0.319925             0.502618
7      0.0        0.0         0.108513             0.123037
8      0.0        1.0         0.159027             0.384817
9      1.0        1.0         0.504210             0.437173
10     1.0        1.0         0.000000             0.345550
11     1.0        1.0         0.514500             0.450262
12     1.0        1.0         0.184284             0.384817
13     1.0        1.0         0.715622             0.821990
14     1.0        1.0         0.363891             0.000000

In [48]:
###QUESTION 2

In [49]:
import pandas as pd
file_path='/content/drive/MyDrive/housing.csv'
df2 = pd.read_csv(file_path)
description = df2.describe()
print(description)

          longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000
mean    -119.569704     35.631861           28.639486   2635.763081
std        2.003532      2.135952           12.585558   2181.615252
min     -124.350000     32.540000            1.000000      2.000000
25%     -121.800000     33.930000           18.000000   1447.750000
50%     -118.490000     34.260000           29.000000   2127.000000
75%     -118.010000     37.710000           37.000000   3148.000000
max     -114.310000     41.950000           52.000000  39320.000000

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000
mean       537.870553   1425.476744    499.539680       3.870671
std        421.385070   1132.462122    382.329753       1.899822
min          1.000000      3.000000      1.000000       0.499900
25%        296.000000    787.000000    280.000000       2.563400
50%        435.000000   1166.000000    409.000000       3.534800
75%        647.000000   1725.000000    605.000000       4.743250
max       6445.000000  35682.000000   6082.000000      15.000100

       median_house_value
count        20640.000000
mean        206855.816909
std         115395.615874
min          14999.000000
25%         119600.000000
50%         179700.000000
75%         264725.000000
max         500001.000000

In [50]:
file_path='/content/drive/MyDrive/housing.csv'
df2=pd.read_csv(file_path)
data_types=df2.dtypes
shape=df2.shape
print("Data Types:")
print(data_types)
print("\nShape:")
print(shape)

Data Types:
longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object

Shape:
(20640, 10)

In [51]:
file_path='/content/drive/MyDrive/housing.csv'
df2=pd.read_csv(file_path)
null_values=df2.isnull().sum()
df2_filled=df2.fillna(0)
print("Null Values:")
print(null_values)
print("\nDataFrame after filling null values:")
print(df2_filled)

Null Values:
longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

DataFrame after filling null values:
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0
1        -122.22     37.86                21.0       7099.0          1106.0
2        -122.24     37.85                52.0       1467.0           190.0
3        -122.25     37.85                52.0       1274.0           235.0
4        -122.25     37.85                52.0       1627.0           280.0
...          ...       ...                 ...          ...             ...
20635    -121.09     39.48                25.0       1665.0           374.0
20636    -121.21     39.49                18.0        697.0           150.0
20637    -121.22     39.43                17.0       2254.0           485.0
20638    -121.32     39.43                18.0       1860.0           409.0
20639    -121.24     39.37                16.0       2785.0           616.0

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0
1          2401.0      1138.0         8.3014            358500.0
2           496.0       177.0         7.2574            352100.0
3           558.0       219.0         5.6431            341300.0
4           565.0       259.0         3.8462            342200.0
...           ...         ...            ...                 ...
20635       845.0       330.0         1.5603             78100.0
20636       356.0       114.0         2.5568             77100.0
20637      1007.0       433.0         1.7000             92300.0
20638       741.0       349.0         1.8672             84700.0
20639      1387.0       530.0         2.3886             89400.0

      ocean_proximity
0            NEAR BAY
1            NEAR BAY
2            NEAR BAY
3            NEAR BAY
4            NEAR BAY
...               ...
20635          INLAND
20636          INLAND
20637          INLAND
20638          INLAND
20639          INLAND

[20640 rows x 10 columns]

In [52]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

df3 = pd.read_csv('/content/drive/MyDrive/housing.csv')

In [53]:
features = df3.drop('ocean_proximity', axis=1)
target = df3['median_house_value']

In [54]:
scaler = MinMaxScaler()
features_normalized = scaler.fit_transform(features)
df_normalized = pd.DataFrame(features_normalized, columns=features.columns)

In [55]:
X_train, X_test, y_train, y_test = train_test_split(df_normalized, target, test_size=0.2, random_state=42)

In [56]:
print("Train set shape:", X_train.shape, y_train.shape)
print("Test set shape:", X_test.shape, y_test.shape)

Train set shape: (16512, 9) (16512,)
Test set shape: (4128, 9) (4128,)